Repository chaosinventory/chaosinventory, pull requests merged in 2021-12, with the labels that each got.

#91 Refactor API serializers
  src/chaosinventory/base/serializers.py
  src/chaosinventory/base/urls.py
  src/chaosinventory/base/views/api.py
Labels: type:enhancement, component:API

#96 Full database configuration via env vars
  src/chaosinventory/settings.py
Labels: type:enhancement, component:Configuration

#97 Remove custom authentication
  src/chaosinventory/authentication/__init__.py
  src/chaosinventory/authentication/admin.py
  src/chaosinventory/authentication/apps.py
  src/chaosinventory/authentication/authentication.py
  src/chaosinventory/authentication/migrations/0001_initial.py
  src/chaosinventory/authentication/migrations/__init__.py
  src/chaosinventory/authentication/models.py
  src/chaosinventory/authentication/serializers.py
  src/chaosinventory/authentication/urls.py
  src/chaosinventory/authentication/views.py
  src/chaosinventory/settings.py
  src/chaosinventory/urls.py
  src/tests/authentication/__init__.py
  src/tests/authentication/test_token.py
  src/tests/base/test_api.py
Labels: level:Breaking Migration, component:Auth

#98 Add some demo data
  src/chaosinventory/base/management/__init__.py
  src/chaosinventory/base/management/commands/__init__.py
  src/chaosinventory/base/management/commands/load_demo_data.py
Labels: type:enhancement

#100 Update documentation to reflect the recent changes
  doc/chaosinventory.cfg
  doc/dev/api/authentication.rst
  doc/dev/api/structure.rst
  doc/dev/frontend/index.rst
  doc/dev/index.rst
  doc/dev/setup/index.rst
  doc/dev/structure/directory.rst
Labels: type:documentation

#101 Provide a login mechanism for the frontend
  src/chaosinventory/base/templates/base.html
  src/chaosinventory/base/templates/base/index.html
  src/chaosinventory/base/templates/base/login.html
  src/chaosinventory/base/urls.py
  src/chaosinventory/base/views/api.py
  src/chaosinventory/settings.py
  src/project-static/src/components/Navbar.jsx
Labels: component:frontend, component:Auth

#102 Send csrf tokens when accessing the api from the frontend
  src/project-static/package-lock.json
  src/project-static/package.json
  src/project-static/src/services/apiService.js
Labels: component:frontend

#103 Fix the item list view in frontend
  src/project-static/src/components/item/ItemForm.jsx
  src/project-static/src/components/item/ItemLabel.jsx
  src/project-static/src/components/item/ItemTable.jsx
  src/project-static/src/components/location/LocationLabel.jsx
  src/project-static/src/components/product/ProductLabel.jsx
  src/project-static/src/components/tag/TagLabel.jsx
  src/project-static/src/components/tag/TagList.jsx
  src/project-static/src/components/tag/TagView.jsx
Labels: component:frontend
