Repository chaosinventory/chaosinventory, pull requests merged in 2021-04, with the labels that each got.

#64 Lint the Linters
  scripts/lint.py
Labels: CI, Quality

#31 Bootstrap REST API
  doc/dev/index.rst
  doc/dev/structure/api.rst
  doc/dev/structure/directory.rst
  doc/dev/structure/index.rst
  doc/requirements.txt
  src/chaosinventory/base/serializers.py
  src/chaosinventory/base/urls.py
  src/chaosinventory/base/views/__init__.py
  src/chaosinventory/base/views/api.py
  src/chaosinventory/settings.py
  src/requirements.txt
  src/setup.cfg
Labels: API, Priority, fundamental

#68 Make list views in admin a bit nicer :D
  src/chaosinventory/base/admin.py
Labels: AdminUI, Next Meeting
